# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Prob 140'
tagline:          'Prob 140'
description:      'Probability for Data Science <br /> Ani Adhikari <br />'
url:              http://probability.gitlab.io
baseurl:          /

author:
  name:           'Dibya Ghosh'
  url:            http://dibya.xyz/beta/

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate,jekyll-gist]

github:
  repo:           https://github.com/poole/hyde
