# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Stat 140'
tagline:          'Stat 140'
description:      'Probability for Data Science <br /> Ani Adhikari <br /> Made by <a href="https://gitlab.com/probability" target="_blank">P4DS</a>.'
url:              http://probability.gitlab.io
baseurl:          /

author:
  name:           'Dibya Ghosh'
  url:            http://data8.org

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate,jekyll-gist]

github:
  repo:           https://github.com/poole/hyde
